id: A4D2A481D
title: 'Opening the Door to a Pure Realm: An Aspiration Towards Abhirati'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:16:24.840985
  last_modified_at: 2022-03-01 00:16:24.840989
