id: A4D2A481D
title: Prayer to the Gurus of the Chöd Lineage
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:16:24.843418
  last_modified_at: 2022-03-01 00:16:24.843422
