id: A4D2A481D
title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
  Jamyang Khyentse Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:16:24.838667
  last_modified_at: 2022-03-01 00:16:24.838675
