id: A4D2A481D
title: Prayer of Aspiration Towards Sukhāvatī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:16:24.842315
  last_modified_at: 2022-03-01 00:16:24.842320
