id: A4D2A481D
title: 'The Swift Fulfilment of Wishes: Prayer for the Swift Appearance of the Supreme
  Tulku of the Mañjughoṣa Guru'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:16:24.844736
  last_modified_at: 2022-03-01 00:16:24.844742
